project:
  type: website
  output-dir: docs

website:
  title: "Sistemes Operatius"
  description: "Grau en Enginyeria Informàtica · Campus Igualada"
  page-navigation: true
  favicon: assets/logo.svg

  page-footer:
    left: |
      Universitat de Lleida · Departament d'Enginyeria Informàtica i Disseny Digital
    right: |
      Construït amb Quarto


  navbar:
    background: "#141e2f"
    title: "SO"
    left:
      - text: "Inici"
        href: index.qmd
      - text: "Guia docent"
        href: https://guiadocent.udl.cat/html/2026-27_105012
    right:
      - icon: github
        href: https://github.com/SO-UdL-EpS/course-site
  sidebar:
    logo: assets/logo.png
    logo-alt: "AMSA Logo"

    style: floating
    collapse-level: 3
    contents:
    - href: course-info/presentation-slides.qmd
      text: "Presentació del curs"
    - href: course-info/contributions/contribute.qmd
      text: "Contribueix al curs"
    - section: "Blocs"
      contents:
        - section: "Bloc 1 · Desenvolupament de Programari en Espai d'Usuari"
          contents:
            - section: Teoria
              contents:
              - href: blocs/01-espai-usuari/teoria/01_rols_funcions.qmd
              - href: blocs/01-espai-usuari/teoria/02_espai_memoria_proces.qmd
              - href: blocs/01-espai-usuari/teoria/03_crides_funcions_cpu_registres_stack.qmd
            - section: "Pralabs"
              contents: 
              - href: blocs/01-espai-usuari/pralabs/01_c_mem.qmd
              - href: blocs/01-espai-usuari/pralabs/02_c_mem.qmd
            - section: "Activitats"
              contents:
              - href: blocs/01-espai-usuari/activitats/01_c_punters_arrays.qmd
              - href: blocs/01-espai-usuari/activitats/01_rols_funcions.qmd
              - href: blocs/01-espai-usuari/activitats/02_espai_funcions.qmd


format:
  udl-course-html:
    toc: true
